### ISSUE TITLE
buildSrc Scripts not supported

### ISSUE THREAD

**Issue by NyCodeGHG** [DRSchlaubi/Intellij-GradleUpdater#9]
When you have a custom supercoolscript.gradle.kts in your buildSrc/main/kotlin, the plugin doesn't recognize it as a Gradle Build Script. So the inspections are not working there.

**Comment by DRSchlaubi** [comment]
that's as this by design , because that would require the plugin to guess whether a string is a gradle dependency or not

in the build.gradle.kts file in order for the inspection to trigger it has to be part of a function call to DepndencyHandler.<configuration name> with a dependency config which intellij actually knows about as it gets compared with the memory gradle project model

or it has to be a Conviguration.invoke() with a property having the same requirements as above

as buildSrc would just offer strings this doesn't work

**Comment by NyCodeGHG** [comment]
😓
